import { StyleSheet } from "react-native";

export const promoStyle = StyleSheet.create({
  searchBar: {
    color: "black",
    backgroundColor: "#fff",
    borderRadius: 10,
    margin: 10,
    padding: 10,
    textAlign: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  checkBox: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  checkBoxContainer: {
    marginLeft: 5,
    marginRight: 5,
    borderWidth: 2,
    borderRadius: 10,
    padding: 5,
    height: 35,
    backgroundColor: "lightgray",
    borderColor: "white",
    opacity: 0.5,
  },
  checkBoxContainerSelected: {
    marginLeft: 5,
    marginRight: 5,
    borderWidth: 2,
    borderRadius: 10,
    padding: 5,
    height: 35,
    backgroundColor: "lightgray",
    borderColor: "white",
    opacity: 1,
  },
  checkBoxText: {
    textAlign: "center",
    marginTop: "auto",
    marginBottom: "auto",
  },
  promoTag: {
    marginTop: 10,
    marginLeft: 5,
    marginRight: 5,
    borderWidth: 2,
    borderRadius: 10,
    height: 35,
    backgroundColor: "lightgray",
    borderColor: "white",
  },
  promoTagText: {
    marginTop: "auto",
    marginBottom: "auto",
    padding: 5,
    fontFamily: "RobotoSlab-Regular",
  },
  promoTagV2: {
    marginTop: 10,
    marginLeft: 5,
    marginRight: 5,
    borderWidth: 2,
    borderRadius: 10,
    height: 35,
    backgroundColor: "darkred",
    borderColor: "white",
  },
  pdfButton: {
    width: 50,
    marginLeft: "auto",
    marginRight: "auto",
    borderWidth: 2,
    borderRadius: 10,
    height: 35,
    backgroundColor: "darkred",
    borderColor: "white",
  },
});
