import { StyleSheet } from "react-native";

export const punctualityCardStyle = StyleSheet.create({
  container: {
    justifyContent: "space-between",
    alignItems: "center",
    alignContent: "center",
    flexDirection: "row",
    backgroundColor: "#fff",
    padding: 10,
    margin: 9,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  textContainer: {
    alignItems: "center",
    width: "100%",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  justifiedText: {
    textAlign: "right",
    fontFamily: "RobotoSlab-Regular",
    fontSize: 15,
    color: "green",
  },
  nonJustifiedText: {
    textAlign: "right",
    fontFamily: "RobotoSlab-Regular",
    fontSize: 15,
    color: "red",
  },
  popUpContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  popUp: {
    backgroundColor: "white",
    width: 350,
    padding: 15,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
  },
  popUpV2: {
    backgroundColor: "white",
    width: 350,
    padding: 15,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
  },
  textArea: {
    height: 340,
    width: 330,
    borderColor: "lightgrey",
    alignItems: "flex-start",
    borderWidth: 1,
    borderRadius: 10,
    textAlignVertical: "top",
    textAlign: "left",
    padding: 10,
    margin: 10,
    fontFamily: "RobotoSlab-Regular",
    color: "black",
  },
  popUpMainText: {
    fontFamily: "RobotoSlab-SemiBold",
    textAlign: "center",
    fontSize: 15,
  },
  popUpMainTextV2: {
    fontFamily: "RobotoSlab-SemiBold",
    textAlign: "center",
    fontSize: 15,
    padding: 30,
  },
  popUpButton: {
    backgroundColor: "#39ace7",
    borderRadius: 10,
    padding: 10,
    width: 100,
    textAlign: "center",
    margin: 10,
  },
  popUpButtonV2: {
    backgroundColor: "gray",
    borderRadius: 10,
    padding: 10,
    width: 100,
    textAlign: "center",
    margin: 10,
  },
});
